model = "gpt-5-codex"
model_reasoning_effort = "high"
network_access = true

[tools]
web_search = true

[mcp_servers.context7]
command = "npx"
args = ["-y", "@upstash/context7-mcp"]

[mcp_servers.playwright]
command = "npx"
args = ["@playwright/mcp@latest"]

[mcp_servers.peekaboo]
command = "npx"
args = ["-y", "@steipete/peekaboo-mcp"]
