- name: Download asdf
  git:
    repo: "{{ repo }}"
    dest: "{{ asdf_dir }}"
    version: master
    accept_hostkey: yes

- name: Link asdf completion config
  file:
    src: "{{ asdf_dir }}/{{ completion_path }}"
    dest: "{{ fish_dir }}/{{ completion_path }}"
    state: link

- name: Check asdf plugins
  shell: fish -lc "asdf plugin-list"
  register: installed_plugins

- name: Add asdf plugins
  shell: fish -lc "asdf plugin-add {{item}}"
  with_items:
    - "{{ plugins }}"
  when: item not in installed_plugins.stdout_lines

- name: Create kerl home directory
  file:
    path: "{{ asdf_dir }}/{{ kerl_home_dir }}"
    state: directory

- name: Link kerl config file
  file:
    src: "{{ kerl_src_dir }}/{{ kerl_config_file }}"
    dest: "{{ asdf_dir }}/{{ kerl_home_dir }}/{{ kerl_config_file }}"
    state: link
