- name: Link config files
  file:
    src: "{{ src_path }}/{{ item }}"
    dest: "~/{{ item }}"
    state: link
  with_items:
    - "{{ config_files }}"

- name: Ensure .claude directory exists
  file:
    path: "~/.claude"
    state: directory
    mode: '0755'

- name: Link .claude settings files
  file:
    src: "{{ src_path }}/.claude/{{ item }}"
    dest: "~/.claude/{{ item }}"
    state: link
    force: yes
  with_items:
    - settings.json
    - settings.local.json

- name: Remove existing commands directory if not a link
  file:
    path: "~/.claude/commands"
    state: absent
  when: ansible_check_mode is not defined

- name: Link .claude/commands directory
  file:
    src: "{{ src_path }}/.claude/commands"
    dest: "~/.claude/commands"
    state: link
    force: yes

- name: Remove existing agents directory if not a link
  file:
    path: "~/.claude/agents"
    state: absent
  when: ansible_check_mode is not defined

- name: Link .claude/agents directory
  file:
    src: "{{ src_path }}/.claude/agents"
    dest: "~/.claude/agents"
    state: link
    force: yes

- name: Link setup-serena-mcp.sh script
  file:
    src: "{{ src_path }}/.claude/setup-serena-mcp.sh"
    dest: "~/.claude/setup-serena-mcp.sh"
    state: link
    force: yes

- name: Ensure .config/zed directory exists
  file:
    path: "~/.config/zed"
    state: directory
    mode: '0755'

- name: Link Zed settings.json
  file:
    src: "{{ src_path }}/editors/zed/settings.json"
    dest: "~/.config/zed/settings.json"
    state: link
    force: yes

- name: Get current global gitignore setting
  shell: git config --global --get core.excludesfile || echo ""
  register: current_gitignore
  changed_when: false

- name: Set global gitignore file
  shell: git config --global core.excludesfile {{ lookup('env', 'HOME') }}/git/dotfiles/.gitignore_global
  when: current_gitignore.stdout != lookup('env', 'HOME') + '/git/dotfiles/.gitignore_global'
