- name: Install homebrew cask packages
  homebrew_cask: 
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ casks }}"
  ignore_errors: yes

- name: Check if sudo-required casks are installed
  command: brew list --cask {{ item }}
  register: sudo_cask_check
  failed_when: false
  changed_when: false
  with_items:
    - "{{ sudo_casks }}"
  loop_control:
    loop_var: item

- name: Notify about manual installation for sudo-required casks
  debug:
    msg: |
      ============================================
      {{ item.item }} is not installed.
      
      Manual installation required because:
      - The installer requires sudo password interactively
      - Homebrew prohibits running as root for security
      
      Please run manually:
      brew install --cask {{ item.item }}
      ============================================
  when: item.rc != 0
  with_items:
    - "{{ sudo_cask_check.results }}"
  loop_control:
    loop_var: item
