---
- name: Disable Apple Press and Hold for VS Code
  shell: defaults write com.microsoft.VSCode ApplePressAndHoldEnabled -bool false
  changed_when: false

- name: Disable Apple Press and Hold for Cursor
  shell: defaults write com.todesktop.230313mzl4w4u92 ApplePressAndHoldEnabled -bool false
  changed_when: false

- name: Create VS Code config directory
  file:
    path: "{{ lookup('env', 'HOME') }}/Library/Application Support/Code/User"
    state: directory
    mode: '0755'

- name: Create Cursor config directory
  file:
    path: "{{ lookup('env', 'HOME') }}/Library/Application Support/Cursor/User"
    state: directory
    mode: '0755'

- name: Create symlink for VS Code settings
  file:
    src: "{{ lookup('env', 'HOME') }}/git/dotfiles/vscode/settings.json"
    dest: "{{ lookup('env', 'HOME') }}/Library/Application Support/Code/User/settings.json"
    state: link
    force: yes

- name: Create symlink for Cursor settings
  file:
    src: "{{ lookup('env', 'HOME') }}/git/dotfiles/cursor/settings.json"
    dest: "{{ lookup('env', 'HOME') }}/Library/Application Support/Cursor/User/settings.json"
    state: link
    force: yes

- name: Create symlink for Cursor keybindings
  file:
    src: "{{ lookup('env', 'HOME') }}/git/dotfiles/cursor/keybindings.json"
    dest: "{{ lookup('env', 'HOME') }}/Library/Application Support/Cursor/User/keybindings.json"
    state: link
    force: yes