# Alacritty configuration for tmux users

[env]
TERM = "xterm-256color"

[window]
padding = { x = 10, y = 10 }
decorations = "full"
opacity = 0.85
dynamic_title = true
# Window dimensions (columns and lines)
dimensions = { columns = 220, lines = 45 }

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
bold_italic = { family = "JetBrainsMono Nerd Font", style = "Bold Italic" }
size = 14.0

[colors.primary]
background = "#0a0a0a"
foreground = "#d4d4d4"

[colors.normal]
black = "#000000"
red = "#cd3131"
green = "#0dbc79"
yellow = "#e5e510"
blue = "#2472c8"
magenta = "#bc3fbc"
cyan = "#11a8cd"
white = "#e5e5e5"

[colors.bright]
black = "#666666"
red = "#f14c4c"
green = "#23d18b"
yellow = "#f5f543"
blue = "#3b8eea"
magenta = "#d670d6"
cyan = "#29b8db"
white = "#e5e5e5"

[selection]
save_to_clipboard = true

[cursor]
style = { shape = "Block", blinking = "On" }
blink_interval = 750

[terminal.shell]
program = "/opt/homebrew/bin/fish"

[keyboard]
bindings = [
  # tmux prefix key passthrough
  { key = "A", mods = "Control", chars = "\u0001" },
  # Copy/Paste for macOS
  { key = "V", mods = "Command", action = "Paste" },
  { key = "C", mods = "Command", action = "Copy" },
  # New window/tab
  { key = "N", mods = "Command", action = "CreateNewWindow" },
  { key = "T", mods = "Command", action = "CreateNewTab" },
  # Font size
  { key = "Plus", mods = "Command", action = "IncreaseFontSize" },
  { key = "Minus", mods = "Command", action = "DecreaseFontSize" },
  { key = "Key0", mods = "Command", action = "ResetFontSize" },
]

[mouse]
hide_when_typing = true
