"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

[user]
name = "cooldaemon"
email = "cooldaemon@gmail.com"

# Work repositories configuration
[[--scope]]
--when.repositories = ["~/git/work"]
[--scope.user]
name = "masahito-ikuta"
email = "ikuta@wovn.io"
